name: lint
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run-linters:
    name: Run linters
    if: (!contains(github.event.pull_request.labels.*.name, 'no lint'))
    concurrency:
      group: lint-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Cache
        id: bun-cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run linters
        run: bun run lint